version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bench
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchdb
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-bench
    ports:
      - "6379:6379"

  app:
    build: ./app
    container_name: go-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      MYSQL_DSN: "root:root@tcp(mysql:3306)/benchdb"
      REDIS_ADDR: "redis:6379"
      ENABLE_CACHE: ${ENABLE_CACHE}
